name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy folder content recursively to remote (clean directory)
      uses: garygrossgarten/github-action-scp@release
      with:
        local: .
        remote: /var/www/j-linn.de/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY}}
        port: ${{ secrets.PORT}}
        rmRemote: true
        dotfiles: false

