name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: archive repository
      run: zip -r archive.zip .
    - name: Print Dir
      run: ls -all
    - name: copy archive
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "archive.zip"
        target: "/var/www/j-linn.de/"
        rm: true
    - name: unzip and remove archive
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: >-
          cd /var/www/j-linn.de/ &&
          unzip archive.zip &&
          rm archive.zip
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        port: ${{ secrets.PORT}}
